#!/bin/bash -l

# TODO: get the env vars from the solve script
source ~/.bashrc
cat ~/.bashrc

# Check that the org auth method exists
ORG_AUTH_METHOD_NAME=$(boundary auth-methods list \
	-scope-id=global \
	-recovery-config /root/boundary-controller-recovery.hcl  \
	-format=json | jq -r '.items[0].name')

if [ "$ORG_AUTH_METHOD_NAME" != "hashicups_auth_method" ]; then
    fail-message "You did not create the 'hashicups_auth_method' auth method."
    exit 1
fi

# Check that the project auth method exists
PROJECT_AUTH_METHOD_NAME=$(boundary auth-methods list \
	-scope-id=$ORG_SCOPE_ID \
	-recovery-config /root/boundary-controller-recovery.hcl  \
	-format=json | jq -r '.items[0].name')

if [ "$PROJECT_AUTH_METHOD_NAME" != "hashicups_auth_method" ]; then
    fail-message "You did not create the 'hashicups_app_auth_method' auth method."
    exit 1
fi

# TODO: check they are in the bashrc

exit 0
