#!/bin/bash -l

# Check that the global auth method exists
GLOBAL_AUTH_METHOD_NAME=$(boundary auth-methods list \
	-recovery-config /root/boundary-controller-recovery.hcl  \
	-scope-id global \
	-format json | jq -r ".items[0].name")

if [ "$GLOBAL_AUTH_METHOD_NAME" != "global_auth_method" ]; then
    fail-message "You did not create the global_auth_method auth method."
    exit 1
fi

# Check that the project auth method exists
ORG_AUTH_METHOD_NAME=$(boundary auth-methods list \
	-recovery-config /root/boundary-controller-recovery.hcl  \
	-scope-id $ORG_SCOPE_ID \
	-format json | jq -r ".items[0].name")

if [ "$ORG_AUTH_METHOD_NAME" != "hashicups_eng_auth_method" ]; then
    fail-message "You did not create the hashicups_eng_app_auth_method auth method."
    exit 1
fi

###
# Check the expected env vars are set
###
if [ "$GLOBAL_AUTH_METHOD_ID" = "" ]; then
    fail-message "You did not set the GLOBAL_AUTH_METHOD_ID env var."
    exit 1
fi

if [ "$ORG_AUTH_METHOD_ID" = "" ]; then
    fail-message "You did not set the ORG_AUTH_METHOD_ID env var."
    exit 1
fi

###
# Check the expected env vars were added to the ~/.bashrc file
###
if ! grep -q 'GLOBAL_AUTH_METHOD_ID' ~/.bashrc; then
    fail-message "You did not add the GLOBAL_AUTH_METHOD_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'ORG_AUTH_METHOD_ID' ~/.bashrc; then
    fail-message "You did not add the ORG_AUTH_METHOD_ID env var to your ~/.bashrc file."
	exit 1
fi

exit 0
