#!/bin/bash -l

###
# Create the org auth method, store the ID in the environment
###
export GLOBAL_AUTH_METHOD_ID=$(boundary auth-methods create password \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-scope-id global \
	-name "global_auth_method" \
	-description "Password auth method for global scope."  \
	-format json | jq -r .item.id)

echo "Global Auth Method ID:" $GLOBAL_AUTH_METHOD_ID
echo "export GLOBAL_AUTH_METHOD_ID=$GLOBAL_AUTH_METHOD_ID" >> ~/.bashrc

###
# Create the project auth method, store the ID in the environment
###
export ORG_AUTH_METHOD_ID=$(boundary auth-methods create password \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-name "hashicups_eng_auth_method" \
	-format json | jq -r .item.id)

echo "Org Auth Method ID:" $ORG_AUTH_METHOD_ID
echo "export ORG_AUTH_METHOD_ID=$ORG_AUTH_METHOD_ID" >> ~/.bashrc

exit 0
