#!/bin/bash -l

# TODO: get the env vars from the solve script
source ~/.bashrc

# Check that the org scope admin role was created
GLOBAL_ADMIN_ROLE_ID=$(boundary roles list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id "global" \
	-format=json | jq -r ".items[1].name")

if [ "$GLOBAL_ADMIN_ROLE_ID" != "global_admin" ]; then
    fail-message "You did not create the `global_admin` role."
    exit 1
fi

# Check that the project scope admin role was created
PROJECT_ADMIN_NAME=$(boundary roles list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format=json | jq -r ".items[1].name")

boundary roles list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format=json | jq -r ".items[1].name"

if [ "$PROJECT_ADMIN_NAME" != "org_admin" ]; then
    fail-message "You did not create the `org_admin` role."
    exit 1
fi

# TODO: check they are in the bashrc

exit 0
