#!/bin/bash -l

###
# Create the Global Admin Role, store the ID in the environment
###
export GLOBAL_ADMIN_ROLE_ID=$(boundary roles create \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-name "global_admin" \
	-scope-id global \
	-format json | jq -r .item.id)

echo "Global Admin Role ID:" $GLOBAL_ADMIN_ROLE_ID
echo "export GLOBAL_ADMIN_ROLE_ID=$GLOBAL_ADMIN_ROLE_ID" >> ~/.bashrc

###
# Create the Org Admin Role, store the ID in the environment
###
export ORG_ADMIN_ROLE_ID=$(boundary roles create \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-name "org_admin" \
	-scope-id global \
	-grant-scope-id $ORG_SCOPE_ID \
	-format json | jq -r .item.id)

echo "Org Admin Role ID:" $ORG_ADMIN_ROLE_ID
echo "export ORG_ADMIN_ROLE_ID=$ORG_ADMIN_ROLE_ID" >> ~/.bashrc

###
# Create the Project Admin Role, store the ID in the environment
###
export PROJECT_ADMIN_ROLE_ID=$(boundary roles create \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-name "project_admin" \
	-scope-id $ORG_SCOPE_ID \
	-grant-scope-id $PROJECT_SCOPE_ID \
	-format json | jq -r .item.id)

echo "Project Admin Role ID:" $PROJECT_ADMIN_ROLE_ID
echo "export PROJECT_ADMIN_ROLE_ID=$PROJECT_ADMIN_ROLE_ID" >> ~/.bashrc

###
# Attach admin grants to each role, store the ID in the environment
###
boundary roles add-grants \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $GLOBAL_ADMIN_ROLE_ID \
	-grant "id=*;type=*;actions=*"

boundary roles add-grants \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $ORG_ADMIN_ROLE_ID \
	-grant "id=*;type=*;actions=*"

boundary roles add-grants \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $PROJECT_ADMIN_ROLE_ID \
	-grant "id=*;type=*;actions=*"

###
# Attach all scope admin grants to the global admin user
###
boundary roles add-principals \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $GLOBAL_ADMIN_ROLE_ID \
	-principal $GLOBAL_ADMIN_USER_ID

boundary roles add-principals \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $ORG_ADMIN_ROLE_ID \
	-principal $GLOBAL_ADMIN_USER_ID

boundary roles add-principals \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $PROJECT_ADMIN_ROLE_ID \
	-principal $GLOBAL_ADMIN_USER_ID

###
# Attach org and project scope admin grants to the org admin user
###
boundary roles add-principals \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $ORG_ADMIN_ROLE_ID \
	-principal $ORG_ADMIN_USER_ID

boundary roles add-principals \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-id $PROJECT_ADMIN_ROLE_ID \
	-principal $ORG_ADMIN_USER_ID

###
# Login as the global admin user, store the token in the environment
###
export BOUNDARY_TOKEN=$(boundary authenticate password \
	-auth-method-id $GLOBAL_AUTH_METHOD_ID \
	-login-name $ADMIN_USERNAME \
	-keyring-type none \
	-password $ADMIN_PASSWORD \
	-format json | jq -r .item.attributes.token)

echo "Boundary Token:" $BOUNDARY_TOKEN
echo "export BOUNDARY_TOKEN=$BOUNDARY_TOKEN" >> ~/.bashrc

exit 0
