#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

export ADMIN_USER_USERNAME="adminuser"
export ADMIN_USER_PASSWORD="adminuser"

# Add Project User Principal to the Project Admin Account
boundary users add-accounts \
-recovery-config /root/boundary-controller-recovery.hcl \
-id $ORG_ADMIN_USER_ID \
-account $ORG_ADMIN_USER_ACCOUNT_ID

export GLOBAL_ANON_LISTING_ID=$( \
boundary roles create -name 'global_anon_listing' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id 'global' \
-format=json | jq -r .item.id)

echo "Global Anon Listing ID:" $GLOBAL_ANON_LISTING_ID

boundary roles add-grants -id $GLOBAL_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=auth-method;actions=list,authenticate' \
-grant 'id=*;type=scope;actions=list,no-op' \
-grant 'id={{account.id}};actions=read,change-password'

boundary roles add-principals -id $GLOBAL_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal 'u_anon'

export ORG_ANON_LISTING_ID=$( \
boundary roles create -name 'org_anon_listing' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id $ORG_SCOPE_ID \
-format=json | jq -r .item.id)

echo "Org Anon Listing ID:" $ORG_ANON_LISTING_ID

boundary roles add-grants -id $ORG_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=auth-method;actions=list,authenticate' \
-grant 'type=scope;actions=list' \
-grant 'id={{account.id}};actions=read,change-password'

boundary roles add-principals -id $ORG_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal 'u_anon'

export GLOBAL_ADMIN_ROLE_ID=$( \
boundary roles create -name 'org_admin' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id 'global' \
-grant-scope-id $ORG_SCOPE_ID \
-format=json | jq -r .item.id)

echo "Global Admin Role ID:" $GLOBAL_ADMIN_ROLE_ID

boundary roles add-grants -id $GLOBAL_ADMIN_ROLE_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=*;actions=*'

boundary roles add-principals -id $GLOBAL_ADMIN_ROLE_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal $ADMIN_USER_ID

export ORG_ADMIN_ROLE_ID=$(
boundary roles create -name 'project_admin' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id $ORG_SCOPE_ID \
-grant-scope-id $PROJECT_SCOPE_ID \
-format=json | jq -r .item.id)

echo "Org Admin Role ID:" $ORG_ADMIN_ROLE_ID

boundary roles add-grants -id $ORG_ADMIN_ROLE_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=*;actions=*'

boundary roles add-principals -id $ORG_ADMIN_ROLE_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal=$ADMIN_USER_ID

export BOUNDARY_TOKEN=$(
boundary authenticate password \
-auth-method-id $PROJECT_AUTH_METHOD_ID \
-login-name=$ADMIN_USER_USERNAME \
-keyring-type=none \
-password=$ADMIN_USER_PASSWORD \
-format=json | jq -r .item.attributes.token
)

echo "export GLOBAL_ANON_LISTING_ID=$GLOBAL_ANON_LISTING_ID" >> ~/.bashrc
echo "export ORG_ANON_LISTING_ID=$ORG_ANON_LISTING_ID" >> ~/.bashrc
echo "export GLOBAL_ADMIN_ROLE_ID=$GLOBAL_ADMIN_ROLE_ID" >> ~/.bashrc
echo "export ORG_ADMIN_ROLE_ID=$ORG_ADMIN_ROLE_ID" >> ~/.bashrc
echo "export ADMIN_USER_USERNAME=$ADMIN_USER_USERNAME" >> ~/.bashrc
echo "export ADMIN_USER_PASSWORD=$ADMIN_USER_PASSWORD" >> ~/.bashrc
echo "export BOUNDARY_TOKEN=$BOUNDARY_TOKEN" >> ~/.bashrc

exit 0
