version: "2"
virtualmachines:
- name: boundary-controller
  image: instruqt-hashicorp/hashistack-0-9-1
  shell: /bin/bash
  machine_type: n1-standard-2
- name: boundary-worker
  image: instruqt-hashicorp/hashistack-0-9-1
  shell: /bin/bash
  machine_type: n1-standard-2
