#!/bin/bash -l

# Check that the host catalog was created.
PROJECT_HOST_CATALOG_ID=$(boundary host-catalogs list \
	-scope-id $PROJECT_SCOPE_ID \
	-format json | jq -r ".items[0].id")

# TODO: this will fail cause it is null at this stage
if [ "$PROJECT_HOST_CATALOG_ID" = "" ]; then
    fail-message "You did not create the Host Catalog."
	exit 1
fi

# Check that the boundary worker host was created.
WORKER_HOST_NAME=$(boundary hosts list \
	-host-catalog-id $PROJECT_HOST_CATALOG_ID \
	-format json | jq -r ".items[0].name")

if [ "$WORKER_HOST_NAME" != "worker-host" ]; then
    fail-message "You did not create the worker host."
	exit 1
fi

# Check that the host set was created.
SSH_HOST_SET_NAME=$(boundary host-sets list \
	-host-catalog-id $PROJECT_HOST_CATALOG_ID \
	-format json | jq -r ".items[0].name")

if [ "$SSH_HOST_SET_NAME" != "test-ssh-host-set" ]; then
    fail-message "You did not create the SSH host set."
	exit 1
fi

# Check that the target was created.
SSH_TARGET_NAME=$(boundary targets list \
	-scope-id $PROJECT_SCOPE_ID \
	-format json | jq -r ".items[0].name")

if [ "$SSH_TARGET_NAME" != "ssh-test-targets" ]; then
    fail-message "You did not create the SSH Target."
	exit 1
fi

###
# Check the expected env vars are set
###
if [ "$PROJECT_HOST_CATALOG_ID" = "" ]; then
    fail-message "You did not set the PROJECT_HOST_CATALOG_ID env var."
    exit 1
fi

if [ "$WORKER_HOST_ID" = "" ]; then
    fail-message "You did not set the WORKER_HOST_ID env var."
    exit 1
fi

if [ "$SSH_HOST_SET_ID" = "" ]; then
    fail-message "You did not set the SSH_HOST_SET_ID env var."
    exit 1
fi

if [ "$SSH_TARGET_ID" = "" ]; then
    fail-message "You did not set the SSH_TARGET_ID env var."
    exit 1
fi

###
# Check the expected env vars were added to the ~/.bashrc file
###
if ! grep -q 'PROJECT_HOST_CATALOG_ID' ~/.bashrc; then
    fail-message "You did not add the PROJECT_HOST_CATALOG_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'WORKER_HOST_ID' ~/.bashrc; then
    fail-message "You did not add the WORKER_HOST_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'SSH_HOST_SET_ID' ~/.bashrc; then
    fail-message "You did not add the SSH_HOST_SET_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'SSH_TARGET_ID' ~/.bashrc; then
    fail-message "You did not add the SSH_TARGET_ID env var to your ~/.bashrc file."
	exit 1
fi

# TODO: Try to log in and check the hostname?

exit 0
