#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

export HOST_CATALOG_ID=$(boundary host-catalogs create static \
	-scope-id=$PROJECT_SCOPE_ID \
	-name="HashiCups App" \
	-description="For HashiCups App usage" \
	-format=json | jq -r .item.id)

echo "Host Catalog ID:" $HOST_CATALOG_ID

export WORKER_HOST_ID=$(boundary hosts create static \
	-name=worker-host \
	-description="Boundary Worker host" \
	-address="boundary-worker" \
	-host-catalog-id=$HOST_CATALOG_ID \
	-format=json | jq -r .item.id)

export HOST_SET_ID=$(boundary host-sets create static \
	-name="test-host-set" \
	-description="Test machine host set" \
	-host-catalog-id=$HOST_CATALOG_ID \
	-format=json | jq -r .item.id)

boundary host-sets add-hosts \
	-id=$HOST_SET_ID \
	-host=$WORKER_HOST_ID

export TARGET_ID=$( boundary targets create tcp \
	-name="ssh-test-targets" \
	-description="Test SSH target" \
	-default-port=22 \
	-scope-id=$PROJECT_SCOPE_ID \
	-session-connection-limit="-1" \
	-format=json | jq -r .item.id)
)

echo "export HOST_CATALOG_ID=$HOST_CATALOG_ID" >> ~/.bashrc
echo "export WORKER_HOST_ID=$WORKER_HOST_ID" >> ~/.bashrc
echo "export HOST_SET_ID=$HOST_SET_ID" >> ~/.bashrc
echo "export TARGET_ID=$TARGET_ID" >> ~/.bashrc

exit 0
