#!/bin/bash -l

###
# Check that the HashiCups org scope exists
###
ORG_SCOPE_NAME=$(boundary scopes list \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-scope-id global \
	-format json | jq -r ".items[0].name")

if [ "$ORG_SCOPE_NAME" != "HashiCups Engineering" ]; then
    fail-message "You did not create the HashiCups Engineering org scope."
	exit 1
fi

###
# Check that the HashiCups App project scope exists
###
PROJECT_SCOPE_NAME=$(boundary scopes list \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format json | jq -r ".items[0].name")

if [ "$PROJECT_SCOPE_NAME" != "HashiCups Web App" ]; then
    fail-message "You did not create the HashiCups Web App project scope."
    exit 1
fi

###
# Check the expected env vars are set
###
if [ "$ORG_SCOPE_ID" = "" ]; then
    fail-message "You did not set the ORG_SCOPE_ID env var."
    exit 1
fi

if [ "$PROJECT_SCOPE_ID" = "" ]; then
    fail-message "You did not set the PROJECT_SCOPE_ID env var."
    exit 1
fi

###
# Check the expected env vars were added to the ~/.bashrc file
###
if ! grep -q 'ORG_SCOPE_ID' ~/.bashrc; then
    fail-message "You did not add the ORG_SCOPE_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'PROJECT_SCOPE_ID' ~/.bashrc; then
    fail-message "You did not add the PROJECT_SCOPE_ID env var to your ~/.bashrc file."
	exit 1
fi

exit 0
