#!/bin/bash -l

#########
# Set up Boundary worker config
#########
cat <<-EOF > /etc/boundary.d/worker.hcl
listener "tcp" {
  purpose = "proxy"
  address = "boundary-worker"
  tls_disable = "true"
}

worker {
  name = "boundary-worker"
  description = "Demo worker instance"
  controllers = [
    "boundary-controller"
  ]
}

# Worker authorization KMS
# Use a production KMS such as Vault or AWS KMS for production installs
kms "aead" {
    purpose = "worker-auth"
    aead_type = "aes-gcm"
    key = "8fZBjCUfN0TzjEGLQldGY4+iE9AkOvCfjh7+p0GtRBQ="
    key_id = "global_worker-auth"
}

disable_mlock = true
EOF

#########
# Run Boundary
#########
sudo chmod 664 /etc/systemd/system/boundary-worker.service
sudo systemctl daemon-reload
sudo systemctl enable boundary-worker
sudo systemctl start boundary-worker
systemctl status boundary-worker

exit 0
