#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

# TODO: check if they exist already due to skipping potentially having an existing one already.

# Create the Org Scope
export ORG_SCOPE_ID=$( \
boundary scopes create -name 'HashiCups Engineering' -scope-id 'global' \
-recovery-config /root/boundary-controller-recovery.hcl \
-skip-admin-role-creation \
-skip-default-role-creation \
-format=json | jq -r .item.id)

echo "Org Scope ID:" $ORG_SCOPE_ID

# Create the Project Scope
export PROJECT_SCOPE_ID=$( \
boundary scopes create -name 'HashiCups Web App' -scope-id $ORG_SCOPE_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-skip-admin-role-creation \
-skip-default-role-creation \
-format=json | jq -r .item.id)

echo "Project Scope ID:" $PROJECT_SCOPE_ID

# Add the environment variables to the .bashrc for future sessions
echo "export ORG_SCOPE_ID=$ORG_SCOPE_ID" >> ~/.bashrc
echo "export PROJECT_SCOPE_ID=$PROJECT_SCOPE_ID" >> ~/.bashrc

exit 0
