#!/bin/bash -l

###
# Check the DBA group exists
###
DBA_GROUP_NAME=$(boundary groups list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format json | jq -r ".items[0].name")

if [ "$DBA_GROUP_NAME" != "dba" ]; then
    fail-message "You did not create the dba group."
    exit 1
fi

###
# Check the PG Read Only Role exists
###
PG_READ_ONLY_ROLE_NAME=$(boundary roles list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format json | jq -r ".items[2].name")

if [ "$PG_READ_ONLY_ROLE_NAME" != "postgres-read-only" ]; then
    fail-message "You did not create the postgres-read-only role."
    exit 1
fi

# TODO: check the principals and grants? Do this elsewhere if so.

###
# Check the DBA account exists
###
DBA_ACCOUNT_NAME=$(boundary accounts list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-auth-method-id $ORG_AUTH_METHOD_ID \
	-format json | jq -r ".items[1].attributes.login_name")

if [ "$DBA_ACCOUNT_NAME" != "dbauser1" ]; then
    fail-message "You did not create the dbauser1 account."
    exit 1
fi

# Check the DBA user exists
DBA_USER_NAME=$(boundary users list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format json | jq -r ".items[1].name")

if [ "$DBA_USER_NAME" != "dbauser1" ]; then
    fail-message "You did not create the dbauser1 user."
    exit 1
fi

# TODO: check the accounts and members were set up properly

###
# Check the expected env vars are set
###
if [ "$DBA_GROUP_ID" = "" ]; then
    fail-message "You did not set the DBA_GROUP_ID env var."
    exit 1
fi

if [ "$PG_READ_ONLY_ROLE_ID" = "" ]; then
    fail-message "You did not set the PG_READ_ONLY_ROLE_ID env var."
    exit 1
fi

if [ "$DBA_USER_ACCOUNT_ID" = "" ]; then
    fail-message "You did not set the DBA_USER_ACCOUNT_ID env var."
    exit 1
fi

if [ "$DBA_USER_ID" = "" ]; then
    fail-message "You did not set the DBA_USER_ID env var."
    exit 1
fi

###
# Check the expected env vars were added to the ~/.bashrc file
###
if ! grep -q 'DBA_GROUP_ID' ~/.bashrc; then
    fail-message "You did not add the DBA_GROUP_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'PG_READ_ONLY_ROLE_ID' ~/.bashrc; then
    fail-message "You did not add the PG_READ_ONLY_ROLE_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'DBA_USER_ACCOUNT_ID' ~/.bashrc; then
    fail-message "You did not add the DBA_USER_ACCOUNT_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'DBA_USER_ID' ~/.bashrc; then
    fail-message "You did not add the DBA_USER_ID env var to your ~/.bashrc file."
	exit 1
fi

exit 0
