#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

export DBA_GROUP_ID=$(boundary groups create \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-name="dba" \
	-description="HashiCups Engineering DBAs" \
	-scope-id=$ORG_SCOPE_ID \
	-format=json | jq -r .item.id)

echo "DBA Group ID:" $DBA_GROUP_ID
echo "export DBA_GROUP_ID=$DBA_GROUP_ID" >> ~/.bashrc

export DBA_USER_ACCOUNT_ID=$(boundary accounts create password \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-login-name "dbauser1" \
	-password "dbauser1" \
	-auth-method-id $ORG_AUTH_METHOD_ID \
	-format=json | jq -r .item.id)

echo "DBA User Account ID:" $DBA_USER_ACCOUNT_ID
echo "export DBA_USER_ACCOUNT_ID=$DBA_USER_ACCOUNT_ID" >> ~/.bashrc

export DBA_USER_ID=$(boundary users create \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-name="dbauser1" \
	-description="An example DBA user." \
	-scope-id=$ORG_SCOPE_ID \
	-format=json | jq -r .item.id)

echo "DBA User ID:" $DBA_USER_ID
echo "export DBA_USER_ID=$DBA_USER_ID" >> ~/.bashrc

# Attach the user to the account
boundary users set-accounts \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-id=$DBA_USER_ID \
	-account=$DBA_USER_ACCOUNT_ID

# Then add the user to the DBA group
boundary groups add-members \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-id=$DBA_GROUP_ID \
	-member=$DBA_USER_ID

exit 0
