#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

export ADMIN_USER_USERNAME="adminuser"
export ADMIN_USER_PASSWORD="foofoofoo"

# Create an Account for Admin User
export ORG_ADMIN_USER_ACCOUNT_ID=$(boundary accounts create password \
-recovery-config /root/boundary-controller-recovery.hcl \
-login-name $ADMIN_USER_USERNAME \
-password $ADMIN_USER_PASSWORD \
-auth-method-id $GLOBAL_AUTH_METHOD_ID \
-format=json | jq -r .item.id)

echo "Org Admin User Account ID:" $ORG_ADMIN_USER_ACCOUNT_ID

export PROJECT_ADMIN_USER_ACCOUNT_ID=$(boundary accounts create password \
-recovery-config /root/boundary-controller-recovery.hcl \
-login-name $ADMIN_USER_USERNAME \
-password $ADMIN_USER_PASSWORD \
-auth-method-id $PROJECT_AUTH_METHOD_ID \
-format=json | jq -r .item.id)

echo "Project Admin User Account ID:" $PROJECT_ADMIN_USER_ACCOUNT_ID

# Create the User Principal for Org Admin User
export ORG_ADMIN_USER_ID=$( \
boundary users create -scope-id global \
-recovery-config /root/boundary-controller-recovery.hcl \
-name $ADMIN_USER_USERNAME \
-description "Admin User for HashiCups Engineering" \
-format=json | jq -r .item.id)

echo "Org Admin User ID:" $ORG_ADMIN_USER_ID

# Add Admin User Principal to the Org Admin Account
boundary users add-accounts \
-recovery-config /root/boundary-controller-recovery.hcl \
-id $ORG_ADMIN_USER_ID \
-account $GLOBAL_ADMIN_USER_ACCOUNT_ID

# Create the User Principal for Project Admin User
export PROJECT_ADMIN_USER_ID=$( \
boundary users create -scope-id $ORG_SCOPE_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-name $ADMIN_USER_USERNAME \
-description "Admin User for HashiCups Web App" \
-format=json | jq -r .item.id)

echo "Project Admin User ID:" $PROJECT_ADMIN_USER_ID

# Add Project User Principal to the Project Admin Account
boundary users add-accounts \
-recovery-config /root/boundary-controller-recovery.hcl \
-id $PROJECT_ADMIN_USER_ID \
-account $PROJECT_ADMIN_USER_ACCOUNT_ID

export GLOBAL_ANON_LISTING_ID=$( \
boundary roles create -name 'global_anon_listing' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id 'global' \
-format=json | jq -r .item.id)

echo "Global Anon Listing ID:" $GLOBAL_ANON_LISTING_ID

boundary roles add-grants -id $GLOBAL_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=auth-method;actions=list,authenticate' \
-grant 'id=*;type=scope;actions=list,no-op' \
-grant 'id={{account.id}};actions=read,change-password'

boundary roles add-principals -id $GLOBAL_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal 'u_anon'

export ORG_ANON_LISTING_ID=$( \
boundary roles create -name 'org_anon_listing' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id $ORG_SCOPE_ID \
-format=json | jq -r .item.id)

echo "Org Anon Listing ID:" $ORG_ANON_LISTING_ID

boundary roles add-grants -id $ORG_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=auth-method;actions=list,authenticate' \
-grant 'type=scope;actions=list' \
-grant 'id={{account.id}};actions=read,change-password'

boundary roles add-principals -id $ORG_ANON_LISTING_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal 'u_anon'

export ORG_ADMIN_ID=$( \
boundary roles create -name 'org_admin' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id 'global' \
-grant-scope-id $ORG_SCOPE_ID \
-format=json | jq -r .item.id)

echo "Org Admin ID:" $ORG_ADMIN_ID

boundary roles add-grants -id $ORG_ADMIN_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=*;actions=*'

boundary roles add-principals -id $ORG_ADMIN_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal $ADMIN_USER_ID

export PROJECT_ADMIN_ID=$(
boundary roles create -name 'project_admin' \
-recovery-config /root/boundary-controller-recovery.hcl \
-scope-id $ORG_SCOPE_ID \
-grant-scope-id $PROJECT_SCOPE_ID \
-format=json | jq -r .item.id)

echo "Project Admin ID:" $PROJECT_ADMIN_ID

boundary roles add-grants -id $PROJECT_ADMIN_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-grant 'id=*;type=*;actions=*'

boundary roles add-principals -id $PROJECT_ADMIN_ID \
-recovery-config /root/boundary-controller-recovery.hcl \
-principal=$ADMIN_USER_ID

export BOUNDARY_TOKEN=$(
boundary authenticate password \
-auth-method-id $PROJECT_AUTH_METHOD_ID \
-login-name=$ADMIN_USER_USERNAME \
-keyring-type=none \
-password=$ADMIN_USER_PASSWORD \
-format=json | jq -r .item.attributes.token
)

echo "export GLOBAL_ADMIN_USER_ACCOUNT_ID=$GLOBAL_ADMIN_USER_ACCOUNT_ID" >> ~/.bashrc
echo "export PROJECT_ADMIN_USER_ACCOUNT_ID=$PROJECT_ADMIN_USER_ACCOUNT_ID" >> ~/.bashrc
echo "export GLOBAL_ANON_LISTING_ID=$GLOBAL_ANON_LISTING_ID" >> ~/.bashrc
echo "export ORG_ANON_LISTING_ID=$ORG_ANON_LISTING_ID" >> ~/.bashrc
echo "export ORG_ADMIN_ID=$ORG_ADMIN_ID" >> ~/.bashrc
echo "export PROJECT_ADMIN_ID=$PROJECT_ADMIN_ID" >> ~/.bashrc
echo "export ADMIN_USER_USERNAME=$ADMIN_USER_USERNAME" >> ~/.bashrc
echo "export ADMIN_USER_PASSWORD=$ADMIN_USER_PASSWORD" >> ~/.bashrc
echo "export BOUNDARY_TOKEN=$BOUNDARY_TOKEN" >> ~/.bashrc

exit 0
