#!/bin/bash -l

# Check that the global scope anon listing role was created
GLOBAL_ANON_LISTING_NAME=$(boundary roles list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id global \
	-format json | jq -r ".items[0].name")

if [ "$GLOBAL_ANON_LISTING_NAME" != "global_anon_listing" ]; then
    fail-message "You did not create the global_anon_listing role."
    exit 1
fi

# Check that the org scope anon listing role was created
ORG_ANON_LISTING_NAME=$(boundary roles list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format json | jq -r ".items[0].name")

if [ "$ORG_ANON_LISTING_NAME" != "org_anon_listing" ]; then
    fail-message "You did not create the org_anon_listing role."
    exit 1
fi

###
# Check the expected env vars are set
###
if [ "$GLOBAL_ANON_LISTING_ID" = "" ]; then
    fail-message "You did not set the GLOBAL_ANON_LISTING_ID env var."
    exit 1
fi

if [ "$ORG_ANON_LISTING_ID" = "" ]; then
    fail-message "You did not set the ORG_ANON_LISTING_ID env var."
    exit 1
fi

###
# Check the expected env vars were added to the ~/.bashrc file
###
if ! grep -q 'GLOBAL_ANON_LISTING_ID' ~/.bashrc; then
    fail-message "You did not add the GLOBAL_ANON_LISTING_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'ORG_ANON_LISTING_ID' ~/.bashrc; then
    fail-message "You did not add the ORG_ANON_LISTING_ID env var to your ~/.bashrc file."
	exit 1
fi

exit 0
