#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

#####
# Create the anonymous listing role for the global scope
#####
export GLOBAL_ANON_LISTING_ID=$(boundary roles create \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-scope-id global \
	-name global_anon_listing \
	-format=json | jq -r .item.id)

echo "Global Anon Listing ID:" $GLOBAL_ANON_LISTING_ID
echo "export GLOBAL_ANON_LISTING_ID=$GLOBAL_ANON_LISTING_ID" >> ~/.bashrc

boundary roles add-grants \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-id $GLOBAL_ANON_LISTING_ID \
	-grant "id=*;type=auth-method;actions=list,authenticate" \
	-grant "id=*;type=scope;actions=list,no-op" \
	-grant "id={{account.id}};actions=read,change-password"

boundary roles add-principals \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-id $GLOBAL_ANON_LISTING_ID \
	-principal "u_anon"

#####
# Create the anonymous listing role for the org scope
#####
export ORG_ANON_LISTING_ID=$(boundary roles create \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-name "org_anon_listing" \
	-scope-id $ORG_SCOPE_ID \
	-format=json | jq -r .item.id)

echo "Org Anon Listing ID:" $ORG_ANON_LISTING_ID
echo "export ORG_ANON_LISTING_ID=$ORG_ANON_LISTING_ID" >> ~/.bashrc

boundary roles add-grants \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-id $ORG_ANON_LISTING_ID \
	-grant "id=*;type=auth-method;actions=list,authenticate" \
	-grant "type=scope;actions=list" \
	-grant "id={{account.id}};actions=read,change-password"

boundary roles add-principals \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-id $ORG_ANON_LISTING_ID \
	-principal "u_anon"

exit 0
