#!/bin/bash -l

# Check that the admin account exists
GLOBAL_ADMIN_USER_ACCOUNT_NAME=$(boundary accounts list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-auth-method-id $GLOBAL_AUTH_METHOD_ID \
	-format json | jq -r ".items[0].attributes.login_name")

echo "Global Auth Method ID:" $GLOBAL_AUTH_METHOD_ID
echo "Global Admin User Account Name:" $GLOBAL_ADMIN_USER_ACCOUNT_NAME

if [ "$GLOBAL_ADMIN_USER_ACCOUNT_NAME" != "admin" ]; then
    fail-message "You did not create the admin account in the global scope."
    exit 1
fi

# Check that the admin account exists
ORG_ADMIN_USER_ACCOUNT_NAME=$(boundary accounts list \
	-recovery-config /root/boundary-controller-recovery.hcl \
	-auth-method-id $ORG_AUTH_METHOD_ID \
	-format json | jq -r ".items[0].attributes.login_name")

if [ "$ORG_ADMIN_USER_ACCOUNT_NAME" != "admin" ]; then
    fail-message "You did not create the admin account for the org auth method."
    exit 1
fi

# TODO: check they are in the bashrc

exit 0
