#!/bin/bash -l

# Check that the admin user exists in the global scope
GLOBAL_ADMIN_USERNAME=$(boundary users list \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-scope-id global \
	-format json | jq -r ".items[-1].name")

if [ "$GLOBAL_ADMIN_USERNAME" != "admin" ]; then
    fail-message "You did not create the admin user in the global scope."
    exit 1
fi

# Check that the admin user exists in the org scope
ORG_ADMIN_USERNAME=$(boundary users list \
	-recovery-config /etc/boundary.d/recovery.hcl \
	-scope-id $ORG_SCOPE_ID \
	-format json | jq -r ".items[-1].name")

if [ "$ORG_ADMIN_USERNAME" != "admin" ]; then
    fail-message "You did not create the admin user in the org scope."
    exit 1
fi

###
# Check the expected env vars are set
###
if [ "$GLOBAL_ADMIN_USER_ID" = "" ]; then
    fail-message "You did not set the GLOBAL_ADMIN_USER_ID env var."
    exit 1
fi

if [ "$ORG_ADMIN_USER_ID" = "" ]; then
    fail-message "You did not set the ORG_ADMIN_USER_ID env var."
    exit 1
fi

###
# Check the expected env vars were added to the ~/.bashrc file
###
if ! grep -q 'GLOBAL_ADMIN_USER_ID' ~/.bashrc; then
    fail-message "You did not add the GLOBAL_ADMIN_USER_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'ORG_ADMIN_USER_ID' ~/.bashrc; then
    fail-message "You did not add the ORG_ADMIN_USER_ID env var to your ~/.bashrc file."
	exit 1
fi

exit 0
