#!/bin/bash -l

# Check that the boundary worker host was created.
POSTGRES_HOST_NAME=$(boundary hosts list \
	-host-catalog-id $PROJECT_HOST_CATALOG_ID \
	-format json | jq -r ".items[-1].name")

if [ "$POSTGRES_HOST_NAME" != "postgres-host" ]; then
    fail-message "You did not create the Postgres host."
	exit 1
fi

# Check that the host set was created.
POSTGRES_HOST_SET_NAME=$(boundary host-sets list \
	-host-catalog-id $PROJECT_HOST_CATALOG_ID \
	-format json | jq -r ".items[-1].name")

if [ "$POSTGRES_HOST_SET_NAME" != "test-postgres-host-set" ]; then
    fail-message "You did not create the Postgres host set."
	exit 1
fi

# Check that the target was created.
POSTGRES_TARGET_NAME=$(boundary targets list \
	-scope-id $PROJECT_SCOPE_ID \
	-format json | jq -r ".items[-1].name")

if [ "$POSTGRES_TARGET_NAME" != "postgres-test-targets" ]; then
    fail-message "You did not create the Postgres Target."
	exit 1
fi

###
# Check the expected env vars are set
###
if [ "$POSTGRES_HOST_ID" = "" ]; then
    fail-message "You did not set the POSTGRES_HOST_ID env var."
    exit 1
fi

if [ "$POSTGRES_HOST_SET_ID" = "" ]; then
    fail-message "You did not set the POSTGRES_HOST_SET_ID env var."
    exit 1
fi

if [ "$POSTGRES_TARGET_ID" = "" ]; then
    fail-message "You did not set the POSTGRES_TARGET_ID env var."
    exit 1
fi

###
# Check the expected env vars were added to the ~/.bashrc file
###
if ! grep -q 'POSTGRES_HOST_ID' ~/.bashrc; then
    fail-message "You did not add the POSTGRES_HOST_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'POSTGRES_HOST_SET_ID' ~/.bashrc; then
    fail-message "You did not add the POSTGRES_HOST_SET_ID env var to your ~/.bashrc file."
	exit 1
fi

if ! grep -q 'POSTGRES_TARGET_ID' ~/.bashrc; then
    fail-message "You did not add the POSTGRES_TARGET_ID env var to your ~/.bashrc file."
	exit 1
fi

exit 0
