#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

export POSTGRES_HOST_ID=$(boundary hosts create static \
	-name=postgres-host \
	-description="Postgres host" \
	-address="localhost" \
	-host-catalog-id=$PROJECT_HOST_CATALOG_ID \
	-format=json | jq -r .item.id)

echo "Postgres Host ID:" $POSTGRES_HOST_ID
echo "export POSTGRES_HOST_ID=$POSTGRES_HOST_ID" >> ~/.bashrc

export POSTGRES_HOST_SET_ID=$(boundary host-sets create static \
	-name="test-postgres-host-set" \
	-description="Postgres machine host set" \
	-host-catalog-id=$PROJECT_HOST_CATALOG_ID \
	-format=json | jq -r .item.id)

echo "Postgres Host Set ID:" $POSTGRES_HOST_SET_ID
echo "export POSTGRES_HOST_SET_ID=$POSTGRES_HOST_SET_ID" >> ~/.bashrc

boundary host-sets add-hosts \
	-id=$POSTGRES_HOST_SET_ID \
	-host=$POSTGRES_HOST_ID

export POSTGRES_TARGET_ID=$(boundary targets create tcp \
	-name="postgres-test-targets" \
	-description="Test Postgres target" \
	-default-port=5432 \
	-scope-id=$PROJECT_SCOPE_ID \
	-session-connection-limit="-1" \
	-format=json | jq -r .item.id)

echo "Postgres Target ID:" $POSTGRES_TARGET_ID
echo "export POSTGRES_TARGET_ID=$POSTGRES_TARGET_ID" >> ~/.bashrc

boundary targets add-host-sets \
	-id=$POSTGRES_TARGET_ID \
	-host-set=$POSTGRES_HOST_SET_ID

# TODO: boundary connect postgres -target-id=$POSTGRES_TARGET_ID
# This is throwing an error

# boundary roles add-grants \
	# -recovery-config /root/boundary-controller-recovery.hcl \
	# -id $ORG_ADMIN_ROLE_ID \
	# -grant 'id=*;type=*;actions=*;output_fields=*'

exit 0
